#!/bin/bash
set -e
if [[ $# -le 1 ]]; then
    echo "Copies the tags from SOURCE to all DESTINATIONS"
    echo "Usage: tagcopy SOURCE DEST1 DEST2 ..."
    exit 1
fi

tags=$(tagget $1)
for f in ${@:2}
do
    if [[ -f "$f" ]]; then
	tag $f $tags
    fi
done

exit 0
